server:
  port: 80
#debug: true
logging:
  config: classpath:log4j2-spring.xml
redis:
  factory:
    host: 10.10.171.165
    port: 6379
    password:
    soTimeOut: 5000
    testOnBorrow: true
    maxTotal: -1
#com:
#  cheuks:
#    bin:
#      original:
#        oauth:
#          login:
#            page:
#              url: https://github.com